name: bank-marketing-mlflow-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.5.2
      - mlflow==2.19.0
      - matplotlib==3.9.2